server:
  port: 8002

spring:
  main:
    # spring boot 2.6.x默认不允许循环依赖, dubbo的这个版本存在循环依赖
    allow-circular-references: true
  profiles:
    superToken: 18988888888
    superUsername: admin
  application:
    name: jeecg-demo-dubbo
  cloud:
    nacos:
      discovery:
        server-addr: @config.server-addr@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml

dubbo:
  application:
    qos-enable: false #关闭dubbo在线运维工具
  cloud:
    subscribed-services: jeecg-system-dubbo #订阅的服务名称，默认订阅所有服务，provider无须订阅服务所以配置为/
