jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: database # 换成nacos可以直接从JSON里读取配置
      group: DEFAULT_GROUP
      data-id: jeecg-gateway-router # jeecg-gateway-router-dubbo # 可选测试Dubbo的配置JSON
spring:
  redis:
    database: 0
    host: jeecg-boot-redis
    port: 6379
    password:
