server:
  port: 8001
spring:
  main:
    # spring boot 2.6.x默认不允许循环依赖, dubbo的这个版本存在循环依赖
    allow-circular-references: true
  #开发环境配置
  profiles:
    active: dev
    superToken: 18988888888
    superUsername: admin
  application:
    name: jeecg-system-dubbo
  cloud:
    nacos:
      discovery:
        server-addr: @config.server-addr@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml

dubbo:
  protocol: # name:采用的协议名称 port:-1代表自动选择端口，默认是：20880
    port: 18888
    name: dubbo
  scan: # dubbo服务路径
    basePackages: org.jeecg.modules
  application:
    qos-enable: false #关闭dubbo在线运维工具
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  cloud:
    subscribed-services: / #订阅的服务名称，默认订阅所有服务，provider无须订阅服务所以配置为/
